interface Product {
  id: string;
  name: string;
  price: number;
  description: string;
  rating: number;
  colors?: string[];
  sizes?: string[];
  scents?: string[];
  images: string[];
  details: string[];
  shipping: string;
  heroimage: string;
  category: string;
  subcategory: string;
}

const mockProducts: Product[] = [
  {
    id: "1",
    name: "Crystal Clear Tumbler",
    price: 25.99,
    description:
      "A stylish and durable tumbler perfect for cold drinks on the go.",
    rating: 4.5,
    colors: ["Clear", "Blue", "Pink"],
    sizes: ["16oz", "24oz"],
    images: ["/assets/images/placeholder.png"],
    details: ["Double-wall insulation", "Fits in car cup holders", "BPA-free"],
    shipping: "Ships within 2-3 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Drinkware",
    subcategory: "Tumblers",
  },
  {
    id: "2",
    name: "Eco-Friendly Water Bottle",
    price: 19.99,
    description: "A reusable water bottle made from eco-friendly materials.",
    rating: 4.7,
    colors: ["Green", "Black"],
    sizes: ["20oz", "32oz"],
    images: ["/assets/images/placeholder.png"],
    details: ["Leak-proof design", "BPA-free", "Lightweight"],
    shipping: "Ships within 1-2 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Drinkware",
    subcategory: "Bottles",
  },
  {
    id: "3",
    name: "Lavender Scented Candle",
    price: 15.99,
    description:
      "Relax with the soothing scent of lavender from this premium candle.",
    rating: 4.9,
    scents: ["Lavender", "Vanilla"],
    images: ["/assets/images/placeholder.png"],
    details: ["Soy wax", "Burn time: 40 hours", "Hand-poured"],
    shipping: "Ships within 3-4 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Fragrances",
    subcategory: "Candles",
  },
  {
    id: "4",
    name: "Sandalwood Wax Melts",
    price: 8.99,
    description:
      "Fill your home with the warm and inviting scent of sandalwood.",
    rating: 4.3,
    scents: ["Sandalwood", "Cedar"],
    images: ["/assets/images/placeholder.png"],
    details: ["Soy wax", "Long-lasting scent"],
    shipping: "Ships within 1-2 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Fragrances",
    subcategory: "Melts",
  },
  {
    id: "5",
    name: "Handmade Soap - Lavender",
    price: 7.99,
    description: "Gentle handmade soap infused with lavender essential oils.",
    rating: 4.8,
    scents: ["Lavender", "Rose"],
    images: ["/assets/images/placeholder.png"],
    details: ["All-natural ingredients", "Sulfate-free", "Cruelty-free"],
    shipping: "Ships within 3-5 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Self-Care",
    subcategory: "Soaps",
  },
  {
    id: "6",
    name: "Eucalyptus Perfume",
    price: 22.99,
    description: "A fresh, invigorating scent perfect for any occasion.",
    rating: 4.4,
    scents: ["Eucalyptus", "Mint"],
    images: ["/assets/images/placeholder.png"],
    details: ["Long-lasting", "Travel-friendly bottle"],
    shipping: "Ships within 2-3 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Self-Care",
    subcategory: "Perfumes",
  },
  {
    id: "7",
    name: "Custom Engraved Pen",
    price: 12.99,
    description: "A sleek and professional pen with custom engraving options.",
    rating: 4.6,
    colors: ["Black", "Silver"],
    images: ["/assets/images/placeholder.png"],
    details: ["Smooth writing", "Refillable ink", "Personalized engraving"],
    shipping: "Ships within 4-5 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Accessories",
    subcategory: "Pens",
  },
  {
    id: "8",
    name: "Leather Keychain",
    price: 9.99,
    description: "A durable leather keychain with customizable initials.",
    rating: 4.5,
    colors: ["Brown", "Black"],
    images: ["/assets/images/placeholder.png"],
    details: ["Genuine leather", "Personalized with initials"],
    shipping: "Ships within 3-4 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Accessories",
    subcategory: "Keyrings",
  },
  {
    id: "9",
    name: "Cozy Winter Jumper",
    price: 35.99,
    description: "Stay warm with this cozy and stylish winter jumper.",
    rating: 4.7,
    colors: ["Gray", "Navy", "Red"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/assets/images/placeholder.png"],
    details: ["Soft wool blend", "Machine washable", "Fits true to size"],
    shipping: "Ships within 5-7 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Apparel",
    subcategory: "Jumpers",
  },
  {
    id: "10",
    name: "Classic Cotton T-Shirt",
    price: 18.99,
    description:
      "A breathable and comfortable cotton t-shirt for everyday wear.",
    rating: 4.3,
    colors: ["White", "Black", "Gray"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/assets/images/placeholder.png"],
    details: ["100% cotton", "Pre-shrunk", "Tagless design"],
    shipping: "Ships within 3-5 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Apparel",
    subcategory: "Shirts",
  },
  {
    id: "11",
    name: "Insulated Travel Mug",
    price: 29.99,
    description:
      "Keep your drinks hot for hours with this sleek insulated travel mug.",
    rating: 4.8,
    colors: ["Black", "White"],
    sizes: ["12oz", "16oz"],
    images: ["/assets/images/placeholder.png"],
    details: ["Double-walled", "Spill-proof lid", "Dishwasher safe"],
    shipping: "Ships within 2-3 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Drinkware",
    subcategory: "Cups",
  },
  {
    id: "12",
    name: "Stainless Steel Bottle",
    price: 24.99,
    description:
      "Durable and reusable stainless steel bottle for any occasion.",
    rating: 4.6,
    colors: ["Silver", "Black", "Blue"],
    sizes: ["20oz", "32oz"],
    images: ["/assets/images/placeholder.png"],
    details: ["Keeps drinks cold for 24 hours", "BPA-free", "Leak-proof"],
    shipping: "Ships within 1-2 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Drinkware",
    subcategory: "Bottles",
  },
  {
    id: "13",
    name: "Ocean Breeze Candle",
    price: 14.99,
    description:
      "Bring the freshness of the ocean into your home with this scented candle.",
    rating: 4.4,
    scents: ["Ocean Breeze", "Citrus"],
    images: ["/assets/images/placeholder.png"],
    details: ["Soy wax", "Burn time: 50 hours"],
    shipping: "Ships within 3-4 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Fragrances",
    subcategory: "Candles",
  },
  {
    id: "14",
    name: "Peppermint Wax Melts",
    price: 9.99,
    description: "Infuse your space with the refreshing scent of peppermint.",
    rating: 4.2,
    scents: ["Peppermint", "Eucalyptus"],
    images: ["/assets/images/placeholder.png"],
    details: ["Soy wax", "Long-lasting fragrance"],
    shipping: "Ships within 1-2 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Fragrances",
    subcategory: "Melts",
  },
  {
    id: "15",
    name: "Cedarwood Soap Bar",
    price: 6.99,
    description:
      "A handmade soap bar with the warm, earthy scent of cedarwood.",
    rating: 4.7,
    scents: ["Cedarwood", "Tea Tree"],
    images: ["/assets/images/placeholder.png"],
    details: ["Vegan", "Cruelty-free", "Handmade"],
    shipping: "Ships within 3-5 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Self-Care",
    subcategory: "Soaps",
  },
  {
    id: "16",
    name: "Rosewater Perfume",
    price: 29.99,
    description: "A light and floral rosewater perfume perfect for daily wear.",
    rating: 4.5,
    scents: ["Rosewater", "Jasmine"],
    images: ["/assets/images/placeholder.png"],
    details: ["Long-lasting", "Travel-sized bottle"],
    shipping: "Ships within 2-3 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Self-Care",
    subcategory: "Perfumes",
  },
  {
    id: "17",
    name: "Elegant Ballpoint Pen",
    price: 14.99,
    description: "A luxury ballpoint pen with a smooth writing experience.",
    rating: 4.6,
    colors: ["Gold", "Silver"],
    images: ["/assets/images/placeholder.png"],
    details: ["Refillable", "Engravable"],
    shipping: "Ships within 4-5 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Accessories",
    subcategory: "Pens",
  },
  {
    id: "18",
    name: "Custom Leather Keyring",
    price: 11.99,
    description: "Personalize your leather keyring with your initials.",
    rating: 4.7,
    colors: ["Brown", "Tan", "Black"],
    images: ["/assets/images/placeholder.png"],
    details: ["Durable leather", "Handmade", "Customizable"],
    shipping: "Ships within 2-3 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Accessories",
    subcategory: "Keyrings",
  },
  {
    id: "19",
    name: "Knitted Winter Jumper",
    price: 39.99,
    description: "A cozy, knitted jumper to keep you warm all winter long.",
    rating: 4.8,
    colors: ["Cream", "Forest Green", "Navy"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/assets/images/placeholder.png"],
    details: ["Wool blend", "Hand-wash only", "Fits true to size"],
    shipping: "Ships within 3-5 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Apparel",
    subcategory: "Jumpers",
  },
  {
    id: "20",
    name: "Classic Crew T-Shirt",
    price: 16.99,
    description: "A classic cotton t-shirt for everyday comfort and style.",
    rating: 4.2,
    colors: ["White", "Gray", "Black"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/assets/images/placeholder.png"],
    details: ["100% cotton", "Machine washable"],
    shipping: "Ships within 2-4 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Apparel",
    subcategory: "Shirts",
  },
  {
    id: "21",
    name: "Reusable Coffee Cup",
    price: 12.99,
    description:
      "A sustainable and reusable coffee cup, perfect for on the go.",
    rating: 4.5,
    colors: ["White", "Black"],
    sizes: ["12oz", "16oz"],
    images: ["/assets/images/placeholder.png"],
    details: ["BPA-free", "Dishwasher safe"],
    shipping: "Ships within 2-3 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Drinkware",
    subcategory: "Cups",
  },
  {
    id: "22",
    name: "Bamboo Water Bottle",
    price: 21.99,
    description: "Eco-friendly bamboo water bottle with a sleek design.",
    rating: 4.3,
    colors: ["Natural", "Black"],
    sizes: ["20oz", "24oz"],
    images: ["/assets/images/placeholder.png"],
    details: ["BPA-free", "Eco-friendly materials"],
    shipping: "Ships within 1-2 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Drinkware",
    subcategory: "Bottles",
  },
  {
    id: "23",
    name: "Vanilla Scented Candle",
    price: 12.99,
    description: "A warm, inviting vanilla scent to relax your space.",
    rating: 4.7,
    scents: ["Vanilla", "Cinnamon"],
    images: ["/assets/images/placeholder.png"],
    details: ["Soy wax", "Burn time: 40 hours"],
    shipping: "Ships within 3-4 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Fragrances",
    subcategory: "Candles",
  },
  {
    id: "24",
    name: "Lavender Wax Melts",
    price: 7.99,
    description:
      "Soothing lavender wax melts for a calm and relaxing ambiance.",
    rating: 4.4,
    scents: ["Lavender", "Chamomile"],
    images: ["/assets/images/placeholder.png"],
    details: ["Soy wax", "Long-lasting scent"],
    shipping: "Ships within 1-2 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Fragrances",
    subcategory: "Melts",
  },
  {
    id: "25",
    name: "Coconut Milk Soap",
    price: 8.99,
    description: "A creamy, moisturizing soap with a fresh coconut milk scent.",
    rating: 4.5,
    scents: ["Coconut", "Vanilla"],
    images: ["/assets/images/placeholder.png"],
    details: ["Sulfate-free", "Handmade"],
    shipping: "Ships within 3-5 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Self-Care",
    subcategory: "Soaps",
  },
  {
    id: "26",
    name: "Citrus Blossom Perfume",
    price: 24.99,
    description: "Bright, zesty citrus blossom fragrance for everyday use.",
    rating: 4.6,
    scents: ["Citrus", "Orange Blossom"],
    images: ["/assets/images/placeholder.png"],
    details: ["Long-lasting", "All-day freshness"],
    shipping: "Ships within 2-3 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Self-Care",
    subcategory: "Perfumes",
  },
  {
    id: "27",
    name: "Metallic Ballpoint Pen",
    price: 9.99,
    description: "Stylish metallic ballpoint pen with smooth writing.",
    rating: 4.3,
    colors: ["Gold", "Silver"],
    images: ["/assets/images/placeholder.png"],
    details: ["Refillable ink", "Comfortable grip"],
    shipping: "Ships within 4-5 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Accessories",
    subcategory: "Pens",
  },
  {
    id: "28",
    name: "Engraved Wooden Keychain",
    price: 8.99,
    description: "Beautifully engraved wooden keychain with customizable text.",
    rating: 4.4,
    colors: ["Natural Wood", "Dark Oak"],
    images: ["/assets/images/placeholder.png"],
    details: ["Customizable", "Durable wood"],
    shipping: "Ships within 2-3 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Accessories",
    subcategory: "Keyrings",
  },
  {
    id: "29",
    name: "Knitted Wool Jumper",
    price: 42.99,
    description: "Stay cozy this winter with our handmade knitted wool jumper.",
    rating: 4.9,
    colors: ["Red", "Gray", "Blue"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/assets/images/placeholder.png"],
    details: ["100% wool", "Hand-wash only"],
    shipping: "Ships within 3-5 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Apparel",
    subcategory: "Jumpers",
  },
  {
    id: "30",
    name: "Graphic Tee",
    price: 18.99,
    description: "A trendy graphic tee perfect for casual wear.",
    rating: 4.1,
    colors: ["White", "Black"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/assets/images/placeholder.png"],
    details: ["100% cotton", "Screen-printed design"],
    shipping: "Ships within 2-4 business days",
    heroimage: "/assets/images/placeholder.png",
    category: "Apparel",
    subcategory: "Shirts",
  },
];
export default mockProducts;
